window.esdocSearchIndex = [
  [
    "lib/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "lib/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "lib/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "lib/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "lib/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "lib/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "lib/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "lib/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "lib/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "lib/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "lib/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "lib/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "lib/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "lib/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "lib/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "lib/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "lib/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "lib/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "lib/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "lib/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "lib/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "lib/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "lib/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "lib/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "lib/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "lib/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "lib/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "lib/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "lib/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "lib/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "lib/.external-ecmascript.js~String",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "lib/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "lib/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "lib/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "lib/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "lib/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "lib/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "lib/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "lib/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "lib/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "lib/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "lib/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "lib/.external-ecmascript.js~function",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "lib/.external-ecmascript.js~null",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "lib/.external-ecmascript.js~number",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "lib/.external-ecmascript.js~object",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "lib/.external-ecmascript.js~string",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "lib/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "lib/associations/base.js",
    "file/lib/associations/base.js.html",
    "lib/associations/base.js",
    "file"
  ],
  [
    "lib/associations/belongs-to-many.js",
    "file/lib/associations/belongs-to-many.js.html",
    "lib/associations/belongs-to-many.js",
    "file"
  ],
  [
    "lib/associations/belongs-to.js",
    "file/lib/associations/belongs-to.js.html",
    "lib/associations/belongs-to.js",
    "file"
  ],
  [
    "lib/associations/has-many.js",
    "file/lib/associations/has-many.js.html",
    "lib/associations/has-many.js",
    "file"
  ],
  [
    "lib/associations/has-one.js",
    "file/lib/associations/has-one.js.html",
    "lib/associations/has-one.js",
    "file"
  ],
  [
    "lib/associations/helpers.js",
    "file/lib/associations/helpers.js.html",
    "lib/associations/helpers.js",
    "file"
  ],
  [
    "lib/associations/index.js",
    "file/lib/associations/index.js.html",
    "lib/associations/index.js",
    "file"
  ],
  [
    "lib/associations/mixin.js",
    "file/lib/associations/mixin.js.html",
    "lib/associations/mixin.js",
    "file"
  ],
  [
    "lib/data-types.js",
    "file/lib/data-types.js.html",
    "lib/data-types.js",
    "file"
  ],
  [
    "lib/deferrable.js",
    "file/lib/deferrable.js.html",
    "lib/deferrable.js",
    "file"
  ],
  [
    "lib/dialects/abstract/connection-manager.js",
    "file/lib/dialects/abstract/connection-manager.js.html",
    "lib/dialects/abstract/connection-manager.js",
    "file"
  ],
  [
    "lib/dialects/abstract/index.js",
    "file/lib/dialects/abstract/index.js.html",
    "lib/dialects/abstract/index.js",
    "file"
  ],
  [
    "lib/dialects/abstract/query-generator/operators.js",
    "file/lib/dialects/abstract/query-generator/operators.js.html",
    "lib/dialects/abstract/query-generator/operators.js",
    "file"
  ],
  [
    "lib/dialects/abstract/query-generator/transaction.js",
    "file/lib/dialects/abstract/query-generator/transaction.js.html",
    "lib/dialects/abstract/query-generator/transaction.js",
    "file"
  ],
  [
    "lib/dialects/abstract/query-interface.js",
    "file/lib/dialects/abstract/query-interface.js.html",
    "lib/dialects/abstract/query-interface.js",
    "file"
  ],
  [
    "lib/dialects/abstract/query.js",
    "file/lib/dialects/abstract/query.js.html",
    "lib/dialects/abstract/query.js",
    "file"
  ],
  [
    "lib/dialects/db2/connection-manager.js",
    "file/lib/dialects/db2/connection-manager.js.html",
    "lib/dialects/db2/connection-manager.js",
    "file"
  ],
  [
    "lib/dialects/db2/data-types.js",
    "file/lib/dialects/db2/data-types.js.html",
    "lib/dialects/db2/data-types.js",
    "file"
  ],
  [
    "lib/dialects/db2/index.js",
    "file/lib/dialects/db2/index.js.html",
    "lib/dialects/db2/index.js",
    "file"
  ],
  [
    "lib/dialects/db2/query-generator.js",
    "file/lib/dialects/db2/query-generator.js.html",
    "lib/dialects/db2/query-generator.js",
    "file"
  ],
  [
    "lib/dialects/db2/query-interface.js",
    "file/lib/dialects/db2/query-interface.js.html",
    "lib/dialects/db2/query-interface.js",
    "file"
  ],
  [
    "lib/dialects/db2/query.js",
    "file/lib/dialects/db2/query.js.html",
    "lib/dialects/db2/query.js",
    "file"
  ],
  [
    "lib/dialects/mariadb/connection-manager.js",
    "file/lib/dialects/mariadb/connection-manager.js.html",
    "lib/dialects/mariadb/connection-manager.js",
    "file"
  ],
  [
    "lib/dialects/mariadb/data-types.js",
    "file/lib/dialects/mariadb/data-types.js.html",
    "lib/dialects/mariadb/data-types.js",
    "file"
  ],
  [
    "lib/dialects/mariadb/index.js",
    "file/lib/dialects/mariadb/index.js.html",
    "lib/dialects/mariadb/index.js",
    "file"
  ],
  [
    "lib/dialects/mariadb/query-generator.js",
    "file/lib/dialects/mariadb/query-generator.js.html",
    "lib/dialects/mariadb/query-generator.js",
    "file"
  ],
  [
    "lib/dialects/mssql/async-queue.js",
    "file/lib/dialects/mssql/async-queue.js.html",
    "lib/dialects/mssql/async-queue.js",
    "file"
  ],
  [
    "lib/dialects/mssql/connection-manager.js",
    "file/lib/dialects/mssql/connection-manager.js.html",
    "lib/dialects/mssql/connection-manager.js",
    "file"
  ],
  [
    "lib/dialects/mssql/data-types.js",
    "file/lib/dialects/mssql/data-types.js.html",
    "lib/dialects/mssql/data-types.js",
    "file"
  ],
  [
    "lib/dialects/mssql/index.js",
    "file/lib/dialects/mssql/index.js.html",
    "lib/dialects/mssql/index.js",
    "file"
  ],
  [
    "lib/dialects/mssql/query-generator.js",
    "file/lib/dialects/mssql/query-generator.js.html",
    "lib/dialects/mssql/query-generator.js",
    "file"
  ],
  [
    "lib/dialects/mssql/query-interface.js",
    "file/lib/dialects/mssql/query-interface.js.html",
    "lib/dialects/mssql/query-interface.js",
    "file"
  ],
  [
    "lib/dialects/mssql/query.js",
    "file/lib/dialects/mssql/query.js.html",
    "lib/dialects/mssql/query.js",
    "file"
  ],
  [
    "lib/dialects/mysql/connection-manager.js",
    "file/lib/dialects/mysql/connection-manager.js.html",
    "lib/dialects/mysql/connection-manager.js",
    "file"
  ],
  [
    "lib/dialects/mysql/data-types.js",
    "file/lib/dialects/mysql/data-types.js.html",
    "lib/dialects/mysql/data-types.js",
    "file"
  ],
  [
    "lib/dialects/mysql/index.js",
    "file/lib/dialects/mysql/index.js.html",
    "lib/dialects/mysql/index.js",
    "file"
  ],
  [
    "lib/dialects/mysql/query-generator.js",
    "file/lib/dialects/mysql/query-generator.js.html",
    "lib/dialects/mysql/query-generator.js",
    "file"
  ],
  [
    "lib/dialects/mysql/query-interface.js",
    "file/lib/dialects/mysql/query-interface.js.html",
    "lib/dialects/mysql/query-interface.js",
    "file"
  ],
  [
    "lib/dialects/parserstore.js",
    "file/lib/dialects/parserStore.js.html",
    "lib/dialects/parserStore.js",
    "file"
  ],
  [
    "lib/dialects/postgres/connection-manager.js",
    "file/lib/dialects/postgres/connection-manager.js.html",
    "lib/dialects/postgres/connection-manager.js",
    "file"
  ],
  [
    "lib/dialects/postgres/data-types.js",
    "file/lib/dialects/postgres/data-types.js.html",
    "lib/dialects/postgres/data-types.js",
    "file"
  ],
  [
    "lib/dialects/postgres/hstore.js",
    "file/lib/dialects/postgres/hstore.js.html",
    "lib/dialects/postgres/hstore.js",
    "file"
  ],
  [
    "lib/dialects/postgres/index.js",
    "file/lib/dialects/postgres/index.js.html",
    "lib/dialects/postgres/index.js",
    "file"
  ],
  [
    "lib/dialects/postgres/query-generator.js",
    "file/lib/dialects/postgres/query-generator.js.html",
    "lib/dialects/postgres/query-generator.js",
    "file"
  ],
  [
    "lib/dialects/postgres/query-interface.js",
    "file/lib/dialects/postgres/query-interface.js.html",
    "lib/dialects/postgres/query-interface.js",
    "file"
  ],
  [
    "lib/dialects/postgres/query.js",
    "file/lib/dialects/postgres/query.js.html",
    "lib/dialects/postgres/query.js",
    "file"
  ],
  [
    "lib/dialects/postgres/range.js",
    "file/lib/dialects/postgres/range.js.html",
    "lib/dialects/postgres/range.js",
    "file"
  ],
  [
    "lib/dialects/snowflake/connection-manager.js",
    "file/lib/dialects/snowflake/connection-manager.js.html",
    "lib/dialects/snowflake/connection-manager.js",
    "file"
  ],
  [
    "lib/dialects/snowflake/data-types.js",
    "file/lib/dialects/snowflake/data-types.js.html",
    "lib/dialects/snowflake/data-types.js",
    "file"
  ],
  [
    "lib/dialects/snowflake/index.js",
    "file/lib/dialects/snowflake/index.js.html",
    "lib/dialects/snowflake/index.js",
    "file"
  ],
  [
    "lib/dialects/snowflake/query-generator.js",
    "file/lib/dialects/snowflake/query-generator.js.html",
    "lib/dialects/snowflake/query-generator.js",
    "file"
  ],
  [
    "lib/dialects/snowflake/query-interface.js",
    "file/lib/dialects/snowflake/query-interface.js.html",
    "lib/dialects/snowflake/query-interface.js",
    "file"
  ],
  [
    "lib/dialects/sqlite/connection-manager.js",
    "file/lib/dialects/sqlite/connection-manager.js.html",
    "lib/dialects/sqlite/connection-manager.js",
    "file"
  ],
  [
    "lib/dialects/sqlite/data-types.js",
    "file/lib/dialects/sqlite/data-types.js.html",
    "lib/dialects/sqlite/data-types.js",
    "file"
  ],
  [
    "lib/dialects/sqlite/index.js",
    "file/lib/dialects/sqlite/index.js.html",
    "lib/dialects/sqlite/index.js",
    "file"
  ],
  [
    "lib/dialects/sqlite/query-generator.js",
    "file/lib/dialects/sqlite/query-generator.js.html",
    "lib/dialects/sqlite/query-generator.js",
    "file"
  ],
  [
    "lib/dialects/sqlite/query-interface.js",
    "file/lib/dialects/sqlite/query-interface.js.html",
    "lib/dialects/sqlite/query-interface.js",
    "file"
  ],
  [
    "lib/dialects/sqlite/query.js",
    "file/lib/dialects/sqlite/query.js.html",
    "lib/dialects/sqlite/query.js",
    "file"
  ],
  [
    "lib/errors/aggregate-error.js",
    "file/lib/errors/aggregate-error.js.html",
    "lib/errors/aggregate-error.js",
    "file"
  ],
  [
    "lib/errors/association-error.js",
    "file/lib/errors/association-error.js.html",
    "lib/errors/association-error.js",
    "file"
  ],
  [
    "lib/errors/base-error.js",
    "file/lib/errors/base-error.js.html",
    "lib/errors/base-error.js",
    "file"
  ],
  [
    "lib/errors/bulk-record-error.js",
    "file/lib/errors/bulk-record-error.js.html",
    "lib/errors/bulk-record-error.js",
    "file"
  ],
  [
    "lib/errors/connection-error.js",
    "file/lib/errors/connection-error.js.html",
    "lib/errors/connection-error.js",
    "file"
  ],
  [
    "lib/errors/connection/access-denied-error.js",
    "file/lib/errors/connection/access-denied-error.js.html",
    "lib/errors/connection/access-denied-error.js",
    "file"
  ],
  [
    "lib/errors/connection/connection-acquire-timeout-error.js",
    "file/lib/errors/connection/connection-acquire-timeout-error.js.html",
    "lib/errors/connection/connection-acquire-timeout-error.js",
    "file"
  ],
  [
    "lib/errors/connection/connection-refused-error.js",
    "file/lib/errors/connection/connection-refused-error.js.html",
    "lib/errors/connection/connection-refused-error.js",
    "file"
  ],
  [
    "lib/errors/connection/connection-timed-out-error.js",
    "file/lib/errors/connection/connection-timed-out-error.js.html",
    "lib/errors/connection/connection-timed-out-error.js",
    "file"
  ],
  [
    "lib/errors/connection/host-not-found-error.js",
    "file/lib/errors/connection/host-not-found-error.js.html",
    "lib/errors/connection/host-not-found-error.js",
    "file"
  ],
  [
    "lib/errors/connection/host-not-reachable-error.js",
    "file/lib/errors/connection/host-not-reachable-error.js.html",
    "lib/errors/connection/host-not-reachable-error.js",
    "file"
  ],
  [
    "lib/errors/connection/invalid-connection-error.js",
    "file/lib/errors/connection/invalid-connection-error.js.html",
    "lib/errors/connection/invalid-connection-error.js",
    "file"
  ],
  [
    "lib/errors/database-error.js",
    "file/lib/errors/database-error.js.html",
    "lib/errors/database-error.js",
    "file"
  ],
  [
    "lib/errors/database/exclusion-constraint-error.js",
    "file/lib/errors/database/exclusion-constraint-error.js.html",
    "lib/errors/database/exclusion-constraint-error.js",
    "file"
  ],
  [
    "lib/errors/database/foreign-key-constraint-error.js",
    "file/lib/errors/database/foreign-key-constraint-error.js.html",
    "lib/errors/database/foreign-key-constraint-error.js",
    "file"
  ],
  [
    "lib/errors/database/timeout-error.js",
    "file/lib/errors/database/timeout-error.js.html",
    "lib/errors/database/timeout-error.js",
    "file"
  ],
  [
    "lib/errors/database/unknown-constraint-error.js",
    "file/lib/errors/database/unknown-constraint-error.js.html",
    "lib/errors/database/unknown-constraint-error.js",
    "file"
  ],
  [
    "lib/errors/eager-loading-error.js",
    "file/lib/errors/eager-loading-error.js.html",
    "lib/errors/eager-loading-error.js",
    "file"
  ],
  [
    "lib/errors/empty-result-error.js",
    "file/lib/errors/empty-result-error.js.html",
    "lib/errors/empty-result-error.js",
    "file"
  ],
  [
    "lib/errors/index.js",
    "file/lib/errors/index.js.html",
    "lib/errors/index.js",
    "file"
  ],
  [
    "lib/errors/instance-error.js",
    "file/lib/errors/instance-error.js.html",
    "lib/errors/instance-error.js",
    "file"
  ],
  [
    "lib/errors/optimistic-lock-error.js",
    "file/lib/errors/optimistic-lock-error.js.html",
    "lib/errors/optimistic-lock-error.js",
    "file"
  ],
  [
    "lib/errors/query-error.js",
    "file/lib/errors/query-error.js.html",
    "lib/errors/query-error.js",
    "file"
  ],
  [
    "lib/errors/sequelize-scope-error.js",
    "file/lib/errors/sequelize-scope-error.js.html",
    "lib/errors/sequelize-scope-error.js",
    "file"
  ],
  [
    "lib/errors/validation-error.js",
    "file/lib/errors/validation-error.js.html",
    "lib/errors/validation-error.js",
    "file"
  ],
  [
    "lib/errors/validation/unique-constraint-error.js",
    "file/lib/errors/validation/unique-constraint-error.js.html",
    "lib/errors/validation/unique-constraint-error.js",
    "file"
  ],
  [
    "lib/generic/falsy.js",
    "file/lib/generic/falsy.js.html",
    "lib/generic/falsy.js",
    "file"
  ],
  [
    "lib/generic/sql-fragment.js",
    "file/lib/generic/sql-fragment.js.html",
    "lib/generic/sql-fragment.js",
    "file"
  ],
  [
    "lib/hooks.js",
    "file/lib/hooks.js.html",
    "lib/hooks.js",
    "file"
  ],
  [
    "lib/index-hints.js",
    "file/lib/index-hints.js.html",
    "lib/index-hints.js",
    "file"
  ],
  [
    "lib/index.js",
    "file/lib/index.js.html",
    "lib/index.js",
    "file"
  ],
  [
    "lib/instance-validator.js",
    "file/lib/instance-validator.js.html",
    "lib/instance-validator.js",
    "file"
  ],
  [
    "lib/model-manager.js",
    "file/lib/model-manager.js.html",
    "lib/model-manager.js",
    "file"
  ],
  [
    "lib/model.js",
    "file/lib/model.js.html",
    "lib/model.js",
    "file"
  ],
  [
    "lib/operators.js",
    "file/lib/operators.js.html",
    "lib/operators.js",
    "file"
  ],
  [
    "lib/query-types.js",
    "file/lib/query-types.js.html",
    "lib/query-types.js",
    "file"
  ],
  [
    "lib/sql-string.js",
    "file/lib/sql-string.js.html",
    "lib/sql-string.js",
    "file"
  ],
  [
    "lib/table-hints.js",
    "file/lib/table-hints.js.html",
    "lib/table-hints.js",
    "file"
  ],
  [
    "lib/transaction.js",
    "file/lib/transaction.js.html",
    "lib/transaction.js",
    "file"
  ],
  [
    "lib/utils.js",
    "file/lib/utils.js.html",
    "lib/utils.js",
    "file"
  ],
  [
    "lib/utils/class-to-invokable.js",
    "file/lib/utils/class-to-invokable.js.html",
    "lib/utils/class-to-invokable.js",
    "file"
  ],
  [
    "lib/utils/deprecations.js",
    "file/lib/utils/deprecations.js.html",
    "lib/utils/deprecations.js",
    "file"
  ],
  [
    "lib/utils/join-sql-fragments.js",
    "file/lib/utils/join-sql-fragments.js.html",
    "lib/utils/join-sql-fragments.js",
    "file"
  ],
  [
    "lib/utils/logger.js",
    "file/lib/utils/logger.js.html",
    "lib/utils/logger.js",
    "file"
  ],
  [
    "lib/utils/validator-extras.js",
    "file/lib/utils/validator-extras.js.html",
    "lib/utils/validator-extras.js",
    "file"
  ]
]