name: CI

on:
  push:
    branches: [master]
  schedule:
    - cron: "0 0 * * *" # every day at midnight
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - uses: actions/setup-node@v2
        with:
          node-version: "10"
      - name: Install
        run: |
          pip install -r requirements.txt
          bundle install
          bundle exec jekyll build
          ./build.sh
          cp -R _site/. site/
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./site
